use_frameworks!

platform :ios, '9.0'

target 'SwiftUIKit_Example' do
  pod 'DeclarativeUI', :path => '../'
  pod 'IQKeyboardManagerSwift'
  target 'SwiftUIKit_Tests' do
    inherit! :search_paths

    
  end
end
